apiVersion: v1
data:
  password: cGFzc3dvcmQxMjM= #password123 i dont care its not vulnerable
  username: YWRtaW51c2Vy #adminuser i dont care its not vulnerable
kind: Secret
metadata:
  creationTimestamp: null
  name: mongo-creds
